[package]
name = "nyasynth"
version = "0.1.0"
authors = ["Aaron Kofsky <aaronko@umich.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug" }
wmidi = "4.0.1"
log = "0.4.17"
simple-logging = "2.0.2"
variant_count = "1.0.0"
derive_more = "0.99"
backtrace = "0.3"
biquad = "0.4.0"
ordered-float = "3.4.0"

# for preset stuff
directories = "4.0.1"
once_cell = "1.7.2"
midly = "0.5.3"
wav = "1.0.0"
clap = { version = "4.1.8", features = ["derive"] }
getrandom = "0.2.8"


[profile.release]
incremental = true
debug = true

[lib]
crate-type = ["cdylib", "lib"]
