[package]
name = "nyasynth"
version = "0.1.0"
authors = ["Aaron Kofsky <aaronko@umich.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nih_plug = { git = "https://github.com/a2aaron/nih-plug.git", rev = "d380c15f8b3047ebe8156884a6afbd3221f1ca79", features = ["vst3", "standalone"]}
derive_more = "0.99"
biquad = "0.4.0"
ordered-float = "3.4.0"

# for preset stuff
midly = "0.5.3"
wav = "1.0.0"
clap = { version = "4.1.8", features = ["derive"] }
getrandom = "0.2.8"


[profile.release]
incremental = true
debug = true

[lib]
crate-type = ["cdylib", "lib"]

[workspace]
members = ["xtask"]